### ISSUE TITLE
.net core

### ISSUE THREAD

**Issue by TaiAivaras** [praveensewak/signalr-shimmy#1]
Hey,

In the description you mention this package is not meant to be used with .net core version of signalR. I was wondering if you could elaborate  why is that? What would need to be done for this to work with .net core?

Thanks!

**Comment by praveensewak** [comment]
I can't seem to find the bug-thread on signalr source - basically remember someone mention that signalR for .net core would have the dep removed in their client library. But just checking now, they haven't. Therefore, I don't see any reason why you couldn't... ¯\_(ツ)_/¯

**Comment by TaiAivaras** [comment]
Huh, i see.. i'll have to give this a try then. Thanks for your input.
