### ISSUE TITLE
Websocket transport url construction

### ISSUE THREAD

**Issue by TaiAivaras** [praveensewak/signalr-shimmy#2]
Hey, i think i found an issue - when trying cors ws communication, wrong url is constructed. I saw you edited getUrl method, but it may still be a bit off. During negotiation host url is appended twice and websocket transport always fails initialising. So yea..

**Comment by praveensewak** [comment]
sorry about that. did you want to make a pull request? otherwise, i can get onto this tonight.

**Comment by praveensewak** [comment]
i have tested and merged a recent pull request. this should resolve incorrect construction of the websocket transport url.

**Comment by vladimir-shmidt** [comment]
hi, this merge lead one more issue. 
**signalR.transports.webSockets** has start method with **webSocketServerUrl** check. That check return url that could be used for signalr connection but then this url is rewriting with **transportLogic.getUrl** method.
So 
**case 1** webSocketServerUrl filled with ws://host/signalr
start 
 url = ws://host/signalr
 transportLogic.getUrl
 url = http://host/signalr?param1=1&etc
**case 2** webSocketServerUrl empty but connection host = host and wsprotocol is ws://
start 
 url = ws://host/signalr
 transportLogic.getUrl
 url = http://host/signalr?param1=1&etc
as a result socket failed as wrong url used 
ws:// schema should be used instead. library version of 0.1.6 hasn't got this issue.
